# Generated by Django 5.1.2 on 2026-03-31 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_name', models.CharField(default='James Smith', max_length=100)),
                ('groom_image', models.ImageField(blank=True, null=True, upload_to='couple/')),
                ('groom_bio_line1', models.TextField(blank=True, help_text="First line of groom's biography", null=True)),
                ('groom_bio_line2', models.TextField(blank=True, help_text="Second line of groom's biography", null=True)),
                ('groom_bio_line3', models.TextField(blank=True, help_text="Third line of groom's biography", null=True)),
                ('bride_name', models.CharField(default='Jane Doe', max_length=100)),
                ('bride_image', models.ImageField(blank=True, null=True, upload_to='couple/')),
                ('bride_bio_line1', models.TextField(blank=True, help_text="First line of bride's biography", null=True)),
                ('bride_bio_line2', models.TextField(blank=True, help_text="Second line of bride's biography", null=True)),
                ('bride_bio_line3', models.TextField(blank=True, help_text="Third line of bride's biography", null=True)),
                ('wedding_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('story', models.TextField(blank=True, help_text='Love story', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('series', models.IntegerField()),
                ('image', models.ImageField(upload_to='event/banners/')),
                ('tagline', models.CharField(blank=True, help_text="E.g. SHAPE YOUR BODY or We're Getting Married", max_length=255)),
                ('title_main', models.CharField(blank=True, help_text='E.g. BE or James', max_length=255, null=True)),
                ('title_highlight', models.CharField(blank=True, help_text='E.g. STRONG or Jane', max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, help_text='E.g. TRAINING HARD or wedding description', max_length=255, null=True)),
                ('button_text', models.CharField(blank=True, default='Get Info', max_length=100)),
                ('pre_title', models.CharField(blank=True, help_text="Small text above title (e.g., We're Getting Married)", max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Hero description text', null=True)),
                ('rsvp_link', models.CharField(blank=True, default='#rsvp', max_length=500, null=True)),
                ('details_link', models.CharField(blank=True, default='#details', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'series'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('location_url', models.CharField(max_length=520)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(choices=[('fas fa-church', 'Ceremony'), ('fas fa-cocktail', 'Cocktail'), ('fas fa-utensils', 'Reception'), ('fas fa-glass-cheers', 'Party'), ('fas fa-calendar-alt', 'Event')], default='fas fa-calendar-alt', max_length=50)),
                ('event_image', models.ImageField(blank=True, help_text='Upload an image for this event', null=True, upload_to='events/')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.couple')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('description', models.TextField(blank=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('attending', models.BooleanField(choices=[(True, 'Yes, Attending'), (False, 'No, Regretfully Declining')])),
                ('guests', models.PositiveIntegerField(default=1)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='WeddingParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('best_man', 'Best Man'), ('maid_honor', 'Maid of Honor'), ('groomsman', 'Groomsman'), ('bridesmaid', 'Bridesmaid'), ('flower_girl', 'Flower Girl'), ('ring_bearer', 'Ring Bearer')], max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='wedding_party/')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_members', to='events.couple')),
            ],
        ),
    ]
