# Generated by Django 5.1.2 on 2026-03-29 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_name', models.CharField(max_length=100)),
                ('bride_name', models.CharField(max_length=100)),
                ('wedding_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('story', models.TextField(blank=True)),
                ('groom_image', models.ImageField(blank=True, upload_to='couple/')),
                ('bride_image', models.ImageField(blank=True, upload_to='couple/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(choices=[('fas fa-church', 'Ceremony'), ('fas fa-cocktail', 'Cocktail'), ('fas fa-utensils', 'Reception'), ('fas fa-glass-cheers', 'Party'), ('fas fa-calendar-alt', 'Event')], default='fas fa-calendar-alt', max_length=50)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.couple')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('description', models.TextField(blank=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('attending', models.BooleanField(choices=[(True, 'Yes, Attending'), (False, 'No, Regretfully Declining')])),
                ('guests', models.PositiveIntegerField(default=1)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='WeddingParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('best_man', 'Best Man'), ('maid_honor', 'Maid of Honor'), ('groomsman', 'Groomsman'), ('bridesmaid', 'Bridesmaid'), ('flower_girl', 'Flower Girl'), ('ring_bearer', 'Ring Bearer')], max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='wedding_party/')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_members', to='events.couple')),
            ],
        ),
    ]
