# Generated by Django 5.1.2 on 2026-03-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couple',
            name='location',
        ),
        migrations.RemoveField(
            model_name='couple',
            name='story',
        ),
        migrations.RemoveField(
            model_name='couple',
            name='wedding_date',
        ),
        migrations.AddField(
            model_name='couple',
            name='bride_bio_line1',
            field=models.TextField(blank=True, help_text="First line of bride's biography", null=True),
        ),
        migrations.AddField(
            model_name='couple',
            name='bride_bio_line2',
            field=models.TextField(blank=True, help_text="Second line of bride's biography", null=True),
        ),
        migrations.AddField(
            model_name='couple',
            name='bride_bio_line3',
            field=models.TextField(blank=True, help_text="Third line of bride's biography", null=True),
        ),
        migrations.AddField(
            model_name='couple',
            name='groom_bio_line1',
            field=models.TextField(blank=True, help_text="First line of groom's biography", null=True),
        ),
        migrations.AddField(
            model_name='couple',
            name='groom_bio_line2',
            field=models.TextField(blank=True, help_text="Second line of groom's biography", null=True),
        ),
        migrations.AddField(
            model_name='couple',
            name='groom_bio_line3',
            field=models.TextField(blank=True, help_text="Third line of groom's biography", null=True),
        ),
        migrations.AlterField(
            model_name='couple',
            name='bride_image',
            field=models.ImageField(blank=True, null=True, upload_to='couple/'),
        ),
        migrations.AlterField(
            model_name='couple',
            name='bride_name',
            field=models.CharField(default='Jane Doe', max_length=100),
        ),
        migrations.AlterField(
            model_name='couple',
            name='groom_image',
            field=models.ImageField(blank=True, null=True, upload_to='couple/'),
        ),
        migrations.AlterField(
            model_name='couple',
            name='groom_name',
            field=models.CharField(default='James Smith', max_length=100),
        ),
    ]
