# Generated by Django 5.1.2 on 2026-03-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_couple_location_remove_couple_story_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='couple',
            name='story',
            field=models.TextField(blank=True, help_text='Love story', null=True),
        ),
        migrations.AddField(
            model_name='couple',
            name='wedding_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
