# Generated by Django 5.1.2 on 2026-03-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_couple_location_couple_story_couple_wedding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, help_text='Upload an image for this event', null=True, upload_to='events/'),
        ),
    ]
