# Generated by Django 5.1.2 on 2026-03-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('series', models.IntegerField()),
                ('image', models.ImageField(upload_to='event/banners/')),
                ('tagline', models.CharField(blank=True, help_text='E.g. SHAPE YOUR BODY', max_length=255)),
                ('title_main', models.CharField(help_text='E.g. BE', max_length=255)),
                ('title_highlight', models.CharField(help_text='E.g. STRONG', max_length=255)),
                ('subtitle', models.CharField(help_text='E.g. TRAINING HARD', max_length=255)),
                ('button_text', models.CharField(blank=True, default='Get Info', max_length=100)),
            ],
        ),
    ]
