# Generated by Django 5.1.2 on 2026-03-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventbanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventbanner',
            options={'ordering': ['order', 'series']},
        ),
        migrations.AddField(
            model_name='eventbanner',
            name='description',
            field=models.TextField(blank=True, help_text='Hero description text', null=True),
        ),
        migrations.AddField(
            model_name='eventbanner',
            name='details_link',
            field=models.CharField(blank=True, default='#details', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eventbanner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventbanner',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventbanner',
            name='pre_title',
            field=models.CharField(blank=True, help_text="Small text above title (e.g., We're Getting Married)", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventbanner',
            name='rsvp_link',
            field=models.CharField(blank=True, default='#rsvp', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='eventbanner',
            name='subtitle',
            field=models.CharField(blank=True, help_text='E.g. TRAINING HARD or wedding description', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventbanner',
            name='tagline',
            field=models.CharField(blank=True, help_text="E.g. SHAPE YOUR BODY or We're Getting Married", max_length=255),
        ),
        migrations.AlterField(
            model_name='eventbanner',
            name='title_highlight',
            field=models.CharField(blank=True, help_text='E.g. STRONG or Jane', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventbanner',
            name='title_main',
            field=models.CharField(blank=True, help_text='E.g. BE or James', max_length=255, null=True),
        ),
    ]
