# Generated by Django 5.1.2 on 2026-03-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventbanner_options_eventbanner_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_url',
            field=models.CharField(default=1, max_length=520),
            preserve_default=False,
        ),
    ]
