# Generated by Django 5.1.2 on 2026-03-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('company_favicon', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('company_logo_svg', models.FileField(blank=True, null=True, upload_to='company/')),
                ('breadcrumb_image', models.FileField(blank=True, null=True, upload_to='company/')),
                ('about_page_image', models.FileField(blank=True, null=True, upload_to='company/')),
                ('offline_address', models.TextField(blank=True, null=True)),
                ('map_location', models.URLField(blank=True, help_text='Google Maps embed URL', null=True)),
                ('info_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('info_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('complaint_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('complaint_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sales_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('sales_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gstn', models.CharField(blank=True, max_length=20, null=True)),
                ('company_instagram', models.URLField(blank=True, null=True)),
                ('company_facebook', models.URLField(blank=True, null=True)),
                ('company_email_ceo', models.EmailField(blank=True, max_length=254, null=True)),
                ('opening_time', models.TimeField(blank=True, default='09:00:00', null=True)),
                ('closing_time', models.TimeField(blank=True, default='17:00:00', null=True)),
                ('closed_days', models.CharField(blank=True, help_text='Comma-separated days (e.g. Sun,Mon)', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Business Detail',
                'verbose_name_plural': 'Business Details',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.CharField(max_length=255, unique=True, verbose_name='Configuration Key')),
                ('value', models.CharField(max_length=255, verbose_name='Configuration Value')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
                'ordering': ['config'],
            },
        ),
    ]
