# Generated by Django 5.1.2 on 2026-02-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='about_page_image',
            field=models.FileField(blank=True, null=True, upload_to='company/'),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='breadcrumb_image',
            field=models.FileField(blank=True, null=True, upload_to='company/'),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='closed_days',
            field=models.CharField(blank=True, help_text='Comma-separated days (e.g. Sun,Mon)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='closing_time',
            field=models.TimeField(blank=True, default='17:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='company_email_ceo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='company_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='company_favicon',
            field=models.ImageField(blank=True, null=True, upload_to='company/'),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='company_instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/'),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='company_logo_svg',
            field=models.FileField(blank=True, null=True, upload_to='company/'),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='company_tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='complaint_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='complaint_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='gstn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='info_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='info_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='map_location',
            field=models.URLField(blank=True, help_text='Google Maps embed URL', null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='offline_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='opening_time',
            field=models.TimeField(blank=True, default='09:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='sales_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='sales_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
