# """
# Django settings for myoceanbasket project.

# Generated by 'django-admin startproject' using Django 5.1.6.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.1/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.1/ref/settings/
# """

# from pathlib import Path
# import os

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-36#s_0_%3y9r$_y_gtkto-0toii4-updm)^8p5)1&l^_+2tb+x'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = ['*']

# CSRF_TRUSTED_ORIGINS = [
#     'http://localhost:8000',   # If running locally
#     'http://127.0.0.1:8000',    # If running locally
#     'https://iron-suite.onrender.com',
# ]

# AUTH_USER_MODEL ='accounts.CustomUser'
# # Application definition

# INSTALLED_APPS = [
#     'accounts',
#     'cms',
#     'enquiry',
#     'products',
#     'orders',
#     'payments',
#     'attendance',
#     'subscriptions',
#     'markdownx',
#     'cloudinary',
#     'django_extensions',
#     'core.apps.CoreConfig',
#     'django_user_agents',
#     'cloudinary_storage',
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     # SSO
#     'allauth',
#     'allauth.account',
#     'allauth.socialaccount',
#     'allauth.socialaccount.providers.google',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     'django_user_agents.middleware.UserAgentMiddleware',
#     # Required by django-allauth
#     "allauth.account.middleware.AccountMiddleware",  
# ]

# ROOT_URLCONF = 'myoceanbasket.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [os.path.join(BASE_DIR,'templates')],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]



# AUTHENTICATION_BACKENDS = (
#     # Needed to login by username in Django admin, regardless of `allauth`
#     "django.contrib.auth.backends.ModelBackend",

#     # `allauth` specific authentication methods, such as login by e-mail
#     "allauth.account.auth_backends.AuthenticationBackend",
# )


# WSGI_APPLICATION = 'myoceanbasket.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
# # from pythonjsonlogger import jsonlogger
# # LOGGING = {
# #     'version': 1,
# #     'disable_existing_loggers': False,
# #     'handlers': {
# #         'graylog': {
# #             'level': 'INFO',
# #             'class': 'core.graylog_handler.GraylogHandler',
# #             'formatter': 'json',
# #         },
# #     },
# #     'formatters': {
# #         'json': {
# #             '()': jsonlogger.JsonFormatter,
# #             'fmt': '%(asctime)s %(levelname)s %(message)s',
# #         },
# #     },
# #     'loggers': {
# #         'django': {
# #             'handlers': ['graylog'],
# #             'level': 'INFO',
# #             'propagate': True,
# #         },
# #     },
# # }


# # Password validation
# # https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'Asia/Kolkata'

# USE_I18N = True

# USE_TZ = True




# LOGIN_URL = '/login/'  # Instead of '/accounts/login/'
# LOGIN_REDIRECT_URL = '/dashboard/'  # Redirects to dashboard after login
# LOGOUT_REDIRECT_URL = '/login/'  # Redirects to login page after logout


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.1/howto/static-files/

# STATIC_URL = '/static/'
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# # MEDIAFILE
# MEDIA_URL = '/media/'


# MEDIA_DIRS = [ os.path.join(BASE_DIR, 'media') ]

# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'


# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

# USERNAME_PREFIX = "MEMBER"
# SUBSCRIPTION_ORDER_PREFIX= "SUB-ORD-DEMO1"


# STATICFILES_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CLOUDINARY_STORAGE = {
#     'CLOUD_NAME': 'myoceanbasket',
#     'API_KEY': '628779972621648',
#     'API_SECRET': 'sNLM0EYtycdFW5xmFx63_Prqn4k'
# }


# ADMIN_PANEL_MODE = 'advanced'  # basic/standard/advanced
# ANONYMOUS_USER_CREATION = False
# SEND_EMAIL = True
# SEND_MESSAGE = True
# MULTI_USER_LOGIN = False
# USE_CLOUDINARY = False
# SUSPEND = False
# USE_WHATSAPP_TWILIO = False
# AI_BOT = False
# ENABLED_MODULES = ['blog', 'basic']
# PAYMENT_MODULES = ['cod','gpay', 'Phonepe', 'Stripe', 'Cards']



# import os
# from dotenv import load_dotenv
# from pathlib import Path

# BASE_DIR = Path(__file__).resolve().parent.parent
# load_dotenv(os.path.join(BASE_DIR, '.env'))
# # Email settings
# EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
# EMAIL_HOST = os.getenv('EMAIL_HOST')
# EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
# EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
# EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False') == 'True'
# EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
# DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
# SITE_NAME = os.getenv('SITE_NAME', 'MySite')

# # Twilio settings
# TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
# TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
# TWILIO_PHONE_NUMBER = os.getenv("TWILIO_PHONE_NUMBER")


# CASHFREE_APP_ID = os.getenv("CASHFREE_APP_ID")
# CASHFREE_SECRET_KEY = os.getenv("CASHFREE_SECRET_KEY")
# GOOGLE_OAUTH_CLIENT_ID = os.getenv("GOOGLE_OAUTH_CLIENT_ID")
# GOOGLE_OAUTH_CLIENT_SECRET = os.getenv("GOOGLE_OAUTH_CLIENT_SECRET")
# GOOGLE_OAUTH_REDIRECT_URI = os.getenv("GOOGLE_OAUTH_REDIRECT_URI")
# GOOGLE_SSO_ALLOWABLE_DOMAINS = []

# # Django-allauth Configuration
# SOCIALACCOUNT_PROVIDERS = {
#     'google': {
#         'SCOPE': ['profile', 'email'],
#         'AUTH_PARAMS': {
#             'access_type': 'online',
#             'redirect_uri': GOOGLE_OAUTH_REDIRECT_URI  
#         },
#         'APP': {
#             'client_id': GOOGLE_OAUTH_CLIENT_ID,
#             'secret': GOOGLE_OAUTH_CLIENT_SECRET,
#         }
#     }
# }

# # settings.py
# SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 days
# SESSION_EXPIRE_AT_BROWSER_CLOSE = False


