# Generated by Django 5.1.2 on 2026-02-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_cleaned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='special_preparation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
