# Generated by Django 5.1.2 on 2026-02-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_vendor_options_remove_vendor_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={},
        ),
        migrations.AlterField(
            model_name='vendor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shop_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
