# Generated by Django 5.1.2 on 2026-02-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_vendor_options_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='staff_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Employee', 'Employee'), ('Vendor', 'Vendor'), ('Customer', 'Customer'), ('Member', 'Member'), ('Trainer', 'Trainer')], max_length=100),
        ),
    ]
