# Generated by Django 5.1.2 on 2026-02-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='staff_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Employee', 'Employee'), ('Vendor', 'Vendor'), ('Customer', 'Customer'), ('Member', 'Member'), ('Rider', 'Rider')], max_length=100),
        ),
    ]
