# Generated by Django 5.1.2 on 2026-03-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='staff_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Employee', 'Employee'), ('Vendor', 'Vendor'), ('Customer', 'Customer'), ('Member', 'Member'), ('Rider', 'Rider'), ('Trader', 'Trader')], max_length=100),
        ),
    ]
