# Generated by Django 5.1.2 on 2026-03-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='app_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='secret_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
