# Generated by Django 5.1.2 on 2026-02-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('none', 'None'), ('flat', 'Flat Amount'), ('percent', 'Percentage')], max_length=20),
        ),
    ]
