# Generated by Django 5.1.2 on 2026-02-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='max_order_quantity',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
    ]
