# Generated by Django 5.1.2 on 2026-03-31 05:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('is_rest_day', models.BooleanField(default=False)),
                ('estimated_duration', models.CharField(default='45-55min', max_length=20)),
                ('warm_up_instructions', models.TextField(default='5-10min mobility + light cardio')),
                ('cool_down_instructions', models.TextField(default='5-10min stretching/breathing')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['weekly_template', 'day'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FitnessLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('beginner', 'Beginner'), ('medium', 'Medium'), ('advanced', 'Advanced'), ('master', 'Master')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('competition', 'Competition'), ('basic_maintenance', 'Basic Maintenance')], max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('muscle_groups', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('safety_notes', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout.equipment')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('exercise', 'Exercise'), ('cardio', 'Cardio'), ('circuit', 'Circuit'), ('rest', 'Rest')], default='exercise', max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('sets', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reps', models.CharField(max_length=20)),
                ('weight_percentage', models.CharField(blank=True, max_length=20)),
                ('rest_time', models.CharField(blank=True, max_length=20)),
                ('estimated_duration', models.CharField(default='10-12min', max_length=20)),
                ('form_cues', models.TextField(blank=True)),
                ('rpe_target', models.CharField(blank=True, max_length=20)),
                ('progression_notes', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('day_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workout.daytemplate')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercise')),
            ],
            options={
                'ordering': ['day_template', 'order'],
                'unique_together': {('day_template', 'order')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_sessions_per_week', models.IntegerField(default=6)),
                ('estimated_duration_per_session', models.CharField(default='45-60min', max_length=20)),
                ('fitness_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.fitnesslevel')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.goal')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserWorkoutAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='assigned', max_length=20)),
                ('custom_notes', models.TextField(blank=True)),
                ('modifications', models.JSONField(blank=True, default=dict)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_workouts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_assignments', to=settings.AUTH_USER_MODEL)),
                ('weekly_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.weeklytemplate')),
            ],
            options={
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.AddField(
            model_name='daytemplate',
            name='weekly_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_templates', to='workout.weeklytemplate'),
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_skipped', models.BooleanField(default=False)),
                ('overall_rpe', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('energy_level', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workout.userworkoutassignment')),
                ('day_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.daytemplate')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('assignment', 'day_template', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets_completed', models.PositiveIntegerField()),
                ('reps_completed', models.CharField(max_length=20)),
                ('weight_used', models.CharField(blank=True, max_length=50)),
                ('actual_rpe', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_completed', models.BooleanField(default=False)),
                ('is_modified', models.BooleanField(default=False)),
                ('modification_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('activity_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.activitytemplate')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='workout.workoutsession')),
            ],
            options={
                'ordering': ['session', 'activity_template__order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='daytemplate',
            unique_together={('weekly_template', 'day')},
        ),
    ]
