# Generated by Django 5.1.2 on 2026-02-01 10:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Compound', 'Compound'), ('Isolation', 'Isolation'), ('Cardio', 'Cardio'), ('Bodyweight', 'Bodyweight'), ('Isometric', 'Isometric')], max_length=50)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('sets', models.IntegerField(default=3)),
                ('reps', models.CharField(default='10-12', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.workoutcategory')),
                ('equipment', models.ManyToManyField(blank=True, to='health.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='MemberWorkoutAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.workouttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutTemplateDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('sets', models.IntegerField(default=3)),
                ('reps', models.CharField(default='10-12', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='health.workouttemplate')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.workoutprogram')),
            ],
        ),
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('week_of_year', models.PositiveSmallIntegerField(db_index=True, editable=False)),
                ('year', models.PositiveSmallIntegerField(db_index=True, editable=False)),
                ('week_index_since_join', models.PositiveIntegerField(db_index=True, editable=False)),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(400)])),
                ('height_cm', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)])),
                ('bmi', models.DecimalField(decimal_places=1, editable=False, max_digits=4, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(60)])),
                ('Vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='accounts.vendor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['Vendor', 'user', 'date'], name='health_body_Vendor__548c1c_idx'), models.Index(fields=['Vendor', 'user', 'year', 'week_of_year'], name='health_body_Vendor__9e3eca_idx'), models.Index(fields=['Vendor', 'user', 'week_index_since_join'], name='health_body_Vendor__7aa840_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
