# Generated by Django 5.1.2 on 2026-02-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionorder',
            name='payment_status',
            field=models.CharField(choices=[('INITIATE', 'Initiate Payment'), ('FETCH_SESSION', 'Fetch Session'), ('GET_ORDER', 'Get Existing Order'), ('CREATE_LINK', 'Create Payment Link'), ('WEBHOOK', 'Webhook'), ('ERROR', 'Error')], default='INITIATE', max_length=20),
        ),
    ]
