# Generated by Django 5.1.2 on 2026-03-31 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before_expiry', models.PositiveIntegerField(default=3)),
                ('message_template', models.TextField(default='Dear {name}, your subscription expires on {expiry}. Please renew.')),
                ('Vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_config', to='accounts.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('message_body', models.TextField()),
                ('Vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_log', to='accounts.vendor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
